/* =========================================================
   data.js  --  Generated by admin panel on 30.03.2026 16:11:22
   Upload this file to your server root to publish changes.
   ========================================================= */
 
const SITE_BASE = {
  "artworks": [
    {
      "id": "untitled-1",
      "title": "Untitled I",
      "titleTR": "İsimsiz I",
      "year": "2024",
      "medium": "Mixed Media",
      "mediumTR": "Karma Teknik",
      "image": null,
      "extraImages": [],
      "model": "images/3d/test.gltf",
      "desc": "Add a description of this artwork — the process, the intent, the materials, the context.",
      "descTR": "Bu eserle ilgili açıklama ekleyin — süreç, niyet, malzeme, bağlam."
    },
    {
      "id": "untitled-2",
      "title": "Untitled II",
      "titleTR": "İsimsiz II",
      "year": "2024",
      "medium": "Digital",
      "mediumTR": "Dijital",
      "image": null,
      "extraImages": [],
      "model": "images/3d/torus_spin.glb",
      "desc": "Add a description of this artwork.",
      "descTR": "Bu eserle ilgili açıklama ekleyin."
    },
    {
      "id": "untitled-3",
      "title": "Untitled III",
      "titleTR": "İsimsiz III",
      "year": "2023",
      "medium": "Print",
      "mediumTR": "Baskı",
      "image": null,
      "extraImages": [],
      "model": null,
      "desc": "Add a description of this artwork.",
      "descTR": "Bu eserle ilgili açıklama ekleyin."
    },
    {
      "id": "untitled-4",
      "title": "Untitled IV",
      "titleTR": "İsimsiz IV",
      "year": "2023",
      "medium": "Oil on Canvas",
      "mediumTR": "Tuval Üzerine Yağlıboya",
      "image": null,
      "extraImages": [],
      "model": null,
      "desc": "Add a description of this artwork.",
      "descTR": "Bu eserle ilgili açıklama ekleyin."
    }
  ],
  "poems": [
    {
      "id": "poem-1",
      "title": "Poem Title One",
      "titleTR": "Şiir Başlık Bir",
      "year": "2024",
      "body": "Add your full poem text here.\nEach line break is preserved exactly.\nThis is where your verses live.\n \nA second stanza can go here,\nseparated by a blank line.",
      "bodyTR": "Şiir metninizi buraya ekleyin.\nHer satır sonu korunur.\nDizeleriniz burada yer alacak.\n \nİkinci kıta buraya gelebilir,\nboş bir satırla ayrılmış şekilde."
    },
    {
      "id": "poem-2",
      "title": "Poem Title Two",
      "titleTR": "Şiir Başlık İki",
      "year": "2024",
      "body": "Second poem goes here.\nAdd as many lines as you like.",
      "bodyTR": "İkinci şiir buraya gelir.\nİstediğiniz kadar satır ekleyebilirsiniz."
    },
    {
      "id": "poem-3",
      "title": "Poem Title Three",
      "titleTR": "Şiir Başlık Üç",
      "year": "2023",
      "body": "Third poem goes here.",
      "bodyTR": "Üçüncü şiir buraya gelir."
    }
  ],
  "articles": [
    {
      "id": "article-1",
      "title": "Article Title One",
      "titleTR": "Makale Başlık Bir",
      "year": "2024",
      "type": "Essay",
      "typeTR": "Deneme",
      "body": "Add your full article text here. This is the body of the essay — you can write as much as you need.\n \nA second paragraph of the article continues here.",
      "bodyTR": "Makale metninizi buraya ekleyin.\n \nMakalenin ikinci paragrafı burada devam eder."
    },
    {
      "id": "article-2",
      "title": "Article Title Two",
      "titleTR": "Makale Başlık İki",
      "year": "2023",
      "type": "Criticism",
      "typeTR": "Eleştiri",
      "body": "Second article body goes here.",
      "bodyTR": "İkinci makale metni buraya gelir."
    }
  ],
  "books": [
    {
      "id": "stain",
      "title": "Stain",
      "titleTR": "Leke",
      "year": "2026",
      "pdf": "books/stainturkish.pdf",
      "cover": null,
      "allowDownload": true,
      "desc": "A collection of poems.",
      "descTR": "Şiirler derlemesi."
    }
  ],
  "projects": [
    {
      "id": "proj-1",
      "title": "Project Title One",
      "titleTR": "Proje Başlık Bir",
      "desc": "A short description of this ongoing project.",
      "descTR": "Bu devam eden projenin kısa açıklaması.",
      "status": "ongoing"
    },
    {
      "id": "proj-2",
      "title": "Project Title Two",
      "titleTR": "Proje Başlık İki",
      "desc": "A short description of this planned project.",
      "descTR": "Bu planlanan projenin kısa açıklaması.",
      "status": "planned"
    }
  ],
  "texts": {
    "aboutEN": "Write your biography or artist statement here. Who you are, where you come from, what you make and why.\n \nA second paragraph about your practice — the themes you return to, the tensions that drive your work.",
    "aboutTR": "Biyografinizi buraya yazın. Kim olduğunuzu, nereden geldiğinizi, ne ürettiğinizi ve neden.\n \nPratiğiniz hakkında ikinci paragraf — döndüğünüz temalar, çalışmalarınızı yönlendiren gerilimler.",
    "contactNote": "Collaborations, exhibitions, publications.",
    "contactNoteTR": "İşbirlikleri, sergiler, yayınlar."
  },
  "artwork": [
    {
      "id": "aw-1774876278445",
      "title": "Life Döner",
      "titleTR": "hayat döner deneme 1",
      "year": "2025",
      "medium": "Sculpture",
      "mediumTR": "Heykel",
      "image": "images/artwork/hayat-doner-deneme2.png",
      "extraImages": [],
      "model": "images/3d/stick.glb",
      "desc": "This work explores the subjective nature of time and the perceptual dimensions of speed. By turning a wheel, the viewer determines the pace of the process, transforming the flow of time into a personal experience. Each rotation leaves new traces on the surface of the clay while simultaneously accelerating the material’s drying process. In this interplay, formation and disappearance, speed and duration, control and chance become visible at once.\n\nThe work materializes the interaction between viewer intervention and material transformation, making the trace of time in matter visible.\n\nIn physics, speed is defined by a simple formula: v = d/t\nHere, v represents speed, d the distance traveled, and t time. Yet this formula relies on the idea of measurable time. The time at the center of this work, however, is not measurable but perceptual.\n\nWhen each viewer turns the wheel at a different pace, not only the mechanical movement changes—the experience of time changes as well. The work therefore reconstructs the idea that time is not absolute but relative within a material process.\n\nEach participant’s interaction individualizes the temporal experience.",
      "descTR": "Bu çalışma, zamanın öznel doğasını ve hızın algısal boyutlarını araştırır. İzleyici bir çarkı çevirerek sürecin hızını belirler ve böylece zamanın akışını kişisel bir deneyime dönüştürür. Her dönüş, çamurun yüzeyinde yeni izler bırakırken malzemenin kuruma sürecini de hızlandırır. Bu süreçte oluş ve yok oluş; hız ve süre; kontrol ve rastlantı aynı anda görünür hâle gelir.\n\nYapıt, izleyici müdahalesi ile malzemenin dönüşümü arasındaki etkileşimi somutlaştırarak zamanın maddede bıraktığı izi görünür kılar.\n\nFizikte hız basit bir formülle tanımlanır: v = d/t\nBurada v hız, d alınan yol, t ise zamandır. Ancak bu formül yalnızca ölçülebilir bir zaman fikrine dayanır. Oysa bu çalışmanın merkezindeki zaman ölçülebilir değil, algılanabilir bir olgudur.\n\nHer izleyici çarkı farklı hızlarda döndürdüğünde yalnızca mekanik hareket değişmez; zamanın deneyimi de dönüşür. Bu nedenle çalışma, “zamanın mutlak değil göreli olduğu” fikrini maddesel bir süreç içinde yeniden kurar.\n\nBu işte her izleyici çarkı farklı hızda döndürdüğünde, zamansal deneyim bireyselleşir."
    }
  ]
};
