/* =============================================================
   data.js  —  Generated by admin panel on 03.04.2026 17:51:08
   Upload this file to your server root to publish changes.
   ============================================================= */

const SITE_BASE = {
  "artworks": [
    {
      "id": "artwork-1774889675037",
      "title": "hayat döner attempt 1",
      "titleTR": "hayat döner deneme 1",
      "year": "2025",
      "desc": "This work explores the subjective nature of time and the perceptual dimensions of speed. By turning a wheel, the viewer determines the pace of the process, transforming the flow of time into a personal experience. Each rotation leaves new traces on the surface of the clay while simultaneously accelerating the material’s drying process. In this interplay, formation and disappearance, speed and duration, control and chance become visible at once.\n\nThe work materializes the interaction between viewer intervention and material transformation, making the trace of time in matter visible.\n\nIn physics, speed is defined by a simple formula: v = d/t\nHere, v represents speed, d the distance traveled, and t time. Yet this formula relies on the idea of measurable time. The time at the center of this work, however, is not measurable but perceptual.\n\nWhen each viewer turns the wheel at a different pace, not only the mechanical movement changes—the experience of time changes as well. The work therefore reconstructs the idea that time is not absolute but relative within a material process.\n\nEach participant’s interaction individualizes the temporal experience.",
      "descTR": "Bu çalışma, zamanın öznel doğasını ve hızın algısal boyutlarını araştırır. İzleyici bir çarkı çevirerek sürecin hızını belirler ve böylece zamanın akışını kişisel bir deneyime dönüştürür. Her dönüş, çamurun yüzeyinde yeni izler bırakırken malzemenin kuruma sürecini de hızlandırır. Bu süreçte oluş ve yok oluş; hız ve süre; kontrol ve rastlantı aynı anda görünür hâle gelir.\n\nYapıt, izleyici müdahalesi ile malzemenin dönüşümü arasındaki etkileşimi somutlaştırarak zamanın maddede bıraktığı izi görünür kılar.\n\nFizikte hız basit bir formülle tanımlanır: v = d/t\nBurada v hız, d alınan yol, t ise zamandır. Ancak bu formül yalnızca ölçülebilir bir zaman fikrine dayanır. Oysa bu çalışmanın merkezindeki zaman ölçülebilir değil, algılanabilir bir olgudur.\n\nHer izleyici çarkı farklı hızlarda döndürdüğünde yalnızca mekanik hareket değişmez; zamanın deneyimi de dönüşür. Bu nedenle çalışma, “zamanın mutlak değil göreli olduğu” fikrini maddesel bir süreç içinde yeniden kurar.\n\nBu işte her izleyici çarkı farklı hızda döndürdüğünde, zamansal deneyim bireyselleşir.",
      "medium": "clay, bearing, 3d print, metal rod, wood",
      "mediumTR": "çamur, rulman, 3d print, metal tij, ahşap",
      "images": [
        {
          "path": "images/artwork/hayatdonerdeneme1/hayatdonerdeneme1-1.png",
          "isMain": false,
          "caption": ""
        },
        {
          "path": "images/artwork/hayatdonerdeneme1/hayatdonerdeneme1-2.jpg",
          "isMain": false,
          "caption": ""
        },
        {
          "path": "images/artwork/hayatdonerdeneme1/hayatdonerdeneme1-3.jpg",
          "isMain": true,
          "caption": ""
        }
      ],
      "materials": [
        {
          "id": "m-1774889761803",
          "type": "image-gallery",
          "label": "Render",
          "content": "",
          "contentTR": "",
          "images": [
            {
              "path": "images/artwork/hayatdonerdeneme1/hayatdonerdeneme1render-1.jpg",
              "caption": ""
            },
            {
              "path": "images/artwork/hayatdonerdeneme1/hayatdonerdeneme1render-2.jpg",
              "caption": ""
            },
            {
              "path": "images/artwork/hayatdonerdeneme1/hayatdonerdeneme1render-4.jpg",
              "caption": ""
            },
            {
              "path": "images/artwork/hayatdonerdeneme1/hayatdonerdeneme1render-5.jpg",
              "caption": ""
            }
          ],
          "path": ""
        },
        {
          "id": "m-1774889828667",
          "type": "pdf",
          "label": "Project Pdf",
          "content": "",
          "contentTR": "",
          "images": [],
          "path": "documents/hayatdonerdeneme1.pdf"
        }
      ],
      "displayImage": null,
      "featured": true,
      "workType": "3d",
      "category": "sculpture"
    },
    {
      "id": "ar-1774892121936",
      "title": "hayat döner attempt 2",
      "titleTR": "hayat döner deneme 2",
      "year": "2025",
      "desc": "This study treats time not as a fixed, unidirectional flow, but as a process continuously reshaped together with the elements that accumulate on it. The serrated raw meatball tray, in which the clay is placed, references a daily kneading action and carries the metaphor of 'being kneaded by time.' In this context, time is conceived not merely as something that passes, but as a force that touches, presses, and gives form.\n\nAt the center of the tray, there is a cylinder that rotates with the help of a bearing. On the surface of this cylinder, formed by joining three strips of packing tape, strip magnets of varying heights have been added. Materials such as metal powder, nails, screws, and pins scattered onto the clay come into contact with the clay as the cylinder rotates, while simultaneously clinging to the cylinder by means of the magnets.\n\nThis process of mutual interaction suggests that time, in the form Bergson described, is not a quantitatively measured flow, but an accumulating and intensifying 'duration.' The rotating cylinder, initially a neutral and mechanical structure representing time, changes and transforms as the process progresses, together with the metal pieces accumulating on it. Thus, time becomes a phenomenon that is not only formative but also shaped by experience. The kneading of the clay and the gradual weighting of the center embody the progression of the past into the present through articulation, in a state of continuity. It makes visible that time is not a fixed, external force; on the contrary, it is a subjective process constantly reconstructed through experience, contact, and accumulation.\n\n",
      "descTR": "Bu çalışma, zamanı sabit ve tek yönlü bir akış olarak değil, üzerinde biriken unsurlarla birlikte sürekli yeniden biçimlenen bir süreç olarak ele alır. Çamurun yerleştirildiği tırtıklı çiğ köfte tepsisi, gündelik bir yoğurma eylemine gönderme yaparak “zamanla yoğrulmak” metaforunu taşır. Bu bağlamda zaman, yalnızca geçen değil; dokunan, bastıran ve biçim veren bir kuvvet olarak düşünülür. Tepsinin merkezinde, rulman yardımıyla dönen bir silindir yer alır. Üç adet koli bandının birleştirilmesiyle oluşturulan bu silindirin yüzeyine, farklı yüksekliklerde şerit mıknatıslar eklenmiştir. Çamurun üzerine serpiştirilen metal tozu, çivi, vida ve toplu iğne gibi malzemeler, silindir döndükçe çamurla temas ederken aynı anda mıknatıslar aracılığıyla silindire tutunur. Bu karşılıklı etkileşim süreci, zamanın Bergson’un tanımladığı biçimiyle nicel olarak ölçülen bir akış değil, biriken ve yoğunlaşan bir “süre” olduğunu düşündürür. Dönen silindir, başlangıçta zamanı temsil eden nötr ve mekanik bir yapı iken, süreç ilerledikçe üzerinde biriken metal parçalarla birlikte değişir ve dönüşür. Böylece zaman, yalnızca biçimlendiren değil, deneyimle birlikte biçimlenen bir olgu hâline gelir. Çamurun yoğrulması ve merkezin giderek ağırlaşması, geçmişin şimdiki ana eklemlenerek süreklilik içinde ilerlemesini somutlaştırır. Zamanın sabit ve dışsal bir kuvvet olmadığını; aksine, yaşantı, temas ve birikim yoluyla sürekli yeniden kurulan öznel bir süreç olduğunu görünür kılar.",
      "medium": "serrated meatball tray, mud, metal powder, bearing, tape, metal, screw, safety pin, nail, strip magnet",
      "mediumTR": "tırtıklı çiğköfte tepsisi, çamur, metal tozu, rulman, bant, metal, vida, toplu iğne, çivi, şerit mıknatıs",
      "images": [
        {
          "path": "images/artwork/hayatdonerdeneme2/hayatdonerdeneme2-1.png",
          "isMain": true,
          "caption": ""
        },
        {
          "path": "images/artwork/hayatdonerdeneme2/hayatdonerdeneme2-2.png",
          "isMain": false,
          "caption": ""
        },
        {
          "path": "images/artwork/hayatdonerdeneme2/hayatdonerdeneme2-3.png",
          "isMain": false,
          "caption": ""
        },
        {
          "path": "images/artwork/hayatdonerdeneme2/hayatdonerdeneme2-4.png",
          "isMain": false,
          "caption": ""
        }
      ],
      "materials": [
        {
          "id": "m-1774892392024",
          "type": "gif",
          "label": "Gif",
          "content": "",
          "contentTR": "",
          "images": [
            {
              "path": "images/artwork/hayatdonerdeneme2/hayatdonerdeme2.gif",
              "caption": ""
            }
          ],
          "path": ""
        },
        {
          "id": "m-1774892410440",
          "type": "3d",
          "label": "3d",
          "content": "",
          "contentTR": "",
          "images": [],
          "path": "images/artwork/hayatdonerdeneme2/hayatdonerdeneme2.gltf"
        },
        {
          "id": "m-1774892428702",
          "type": "pdf",
          "label": "Pdf",
          "content": "",
          "contentTR": "",
          "images": [],
          "path": "images/artwork/hayatdonerdeneme2/hayatdonerdeneme2.pdf"
        }
      ],
      "displayImage": null,
      "featured": false,
      "workType": "3d",
      "category": "sculpture"
    },
    {
      "id": "ar-1774892777816",
      "title": "hayat döner attempt 3",
      "titleTR": "hayat döner deneme 3",
      "year": "2026",
      "desc": "This study questions the assumption that time is a fully comprehensible, uninterrupted, and simultaneous structure. The fact that the 360-degree surface of a cylinder cannot be seen without rotating it points to a structural limitation of temporal experience. Similarly, time can only be experienced through the present moment; the past and the future remain invisible, staying outside the field of direct perception.\n\nIn the sculpture, this invisibility finds a material counterpart through the clay mass. The clay represents the idea that the past and the future are concealed not because of distance, but because they are covered by the matter of the present. The horizon ceases to be a space opening forward; it becomes a possibility buried, hidden, and deferred within the present.\n\nThe fixed spring that wraps around the cylinder in an S-shape is positioned not as a mechanism that measures or activates time, but as a carrier of temporal tension. This structure, which gives the impression of being about to snap, aligns with the meaning Benjamin Walter's Jetztzeit: here, time is not in a state of flow; it exists as an internally charged, compressed intensity that carries the potential to rupture at any moment.\n\nIn this context, the sculpture does not so much represent time as suspend it. Rather than offering the viewer a progressive continuity, it proposes an experience of temporal tension trapped within the present. Thus, in alignment with Benjamin's concept of Jetztzeit, the work makes visible the discontinuous and conflictual nature of time, in opposition to a linear understanding of history.\n\n\"Jetztzeit (Now-time) is the moment in which fragments of messianic time are embedded.",
      "descTR": "Bu çalışma, zamanın bütünüyle kavranabilir, kesintisiz ve eşzamanlı bir yapı olduğu varsayımını sorgular. Bir silindirin 360 derecelik yüzeyinin, dönmeden aynı anda görülememesi, zamansal deneyimin yapısal bir sınırlılığına işaret eder. Zaman da benzer biçimde, yalnızca içinde bulunulan an üzerinden deneyimlenebilir; geçmiş ve gelecek, algının doğrudan alanı dışında kalarak görünmezleşir.\n\nHeykelde bu görünmezlik, çamur kütlesi aracılığıyla maddesel bir karşılık bulur. Çamur, geçmiş ve geleceğin bir mesafe nedeniyle değil, şimdinin maddesi tarafından örtülmesi fikrini temsil eder. Ufuk, ileriye doğru açılan bir alan olmaktan çıkar; şimdiye gömülmüş, saklanmış ve ertelenmiş bir olasılık hâline gelir.\n\nSilindirin etrafını S formunda saran sabit yay, zamanı ölçen ya da harekete geçiren bir mekanizma olarak değil, zamansal gerilimin taşıyıcısı olarak konumlanır. Kopmak üzereymiş izlenimi veren bu yapı, Jetztzeit’in Benjamin’de kazandığı anlamla örtüşür: Zaman, burada akış hâlinde değil; içsel olarak yüklü, sıkışmış ve her an kırılma potansiyeli taşıyan bir yoğunluk olarak mevcuttur.\n\nBu bağlamda heykel, zamanı temsil etmekten çok, onu askıya alır. İzleyiciye ilerleyen bir süreklilik sunmak yerine, şimdiye hapsolmuş bir zamansal gerilim deneyimi önerir. Böylece çalışma, lineer tarih anlayışına karşı, Benjamin’in Jetztzeit kavramıyla uyumlu biçimde, zamanın kesintili ve çatışmalı doğasını görünür kılar.\n\n“Jetztzeit (Şimdi-zaman), mesiyanik zamanın parçalarının içine saplandığı andır.”",
      "medium": "çamur, yay",
      "mediumTR": "clay, spring",
      "images": [
        {
          "path": "images/artwork/hayatdonerdeneme3/hayatdonerdeneme3-1.jpg",
          "isMain": false,
          "caption": ""
        },
        {
          "path": "images/artwork/hayatdonerdeneme3/hayatdonerdeneme3-2.jpg",
          "isMain": true,
          "caption": ""
        },
        {
          "path": "images/artwork/hayatdonerdeneme3/hayatdonerdeneme3-3.jpg",
          "isMain": false,
          "caption": ""
        }
      ],
      "materials": [
        {
          "id": "m-1774893016846",
          "type": "3d",
          "label": "3d",
          "content": "",
          "contentTR": "",
          "images": [],
          "path": "images/artwork/hayatdonerdeneme3/deneme3.gltf"
        },
        {
          "id": "m-1774893055188",
          "type": "pdf",
          "label": "Pdf",
          "content": "",
          "contentTR": "",
          "images": [],
          "path": "images/artwork/hayatdonerdeneme3/hayat-döner-deneme-3.pdf"
        }
      ],
      "displayImage": null,
      "featured": false,
      "workType": "3d",
      "category": "sculpture"
    },
    {
      "id": "ar-1774893786854",
      "title": "gabriel's clarion",
      "titleTR": "israfil'in zurnası",
      "year": "2026",
      "desc": "This sculpture project is an experimental work that combines the phenomenon of Gabriel’s Horn embodying the tension between mathematical infinity and physical experience with the fluid nature of time.\n\nA pipe section approximately 60 cm long represents only a fragment of the mathematical object that extends toward infinity, yet it functions metonymically by pointing to the whole. From the tip of the pipe, an IV drip is positioned high above and wrapped around Gabriel’s Horn in a spiral form. Through evenly spaced holes opened along the tube, water continuously moistens the clay. This moistening occurs in proportion to gravity and time.\n\nOver the course of approximately two weeks, I will document the form and texture the clay takes through this experiment. In this setup, the flow of water unfolds in direct relation to gravity and time. During this two-week process, the traces left by water on the clay, the textures it creates, and the transformations of form are recorded regularly. Every moment in which water meets clay becomes a witness to the visibility of time’s traces upon matter.",
      "descTR": "Bu heykel projesi, matematiksel sonsuzluk ile fizik\nsel deneyim arasındaki gerilimi somutlaştıran Gabriel’in \nBorusu fenomenini, zamanın akışkan doğasıyla birleştiren \ndeneysel bir çalışmadır. Yaklaşık 60 cm uzunluğundaki \nbir boru kesiti, matematiksel nesnenin sonsuzluğa uzanan \nyapısının yalnızca bir parçasını temsil ederken, aslın\nda bütüne işaret eden bir metonim işlevi görür. Borunun \nucundan yükseğe yerleştirilmiş bir hastane serumu Gabri\nel’in Borusu etrafında spiral bir form oluşturacak şekil\nde sarılmıştır. Hortum üzerinde eşit aralıklarla açılmış \ndelikler aracılığı ile çamurun üzerini devamlı olarak \nıslatır. Bu ıslatma yerçekimi ve zaman ile orantılı bir \nşekildedir. Yaklaşık iki hafta boyunca çamurun bu deney \nsayesinde aldığı şekli ve dokuyu dokümente edeceğim.\nBu düzenekte suyun akışı, yerçekimi ve zamanla orantılı \nbir biçimde gerçekleşiyor. Yaklaşık iki hafta boyunca \ndevam edecek bu süreçte, suyun çamur üzerinde bıraktığı \nizler, oluşturduğu dokular ve şekil değişimleri düzen\nli olarak belgeleniyor. Suyun çamurla buluştuğu her an \nzamanın izlerinin madde üzerinde görünür kılınmasına \ntanıklık ediyor",
      "medium": "Sculpture",
      "mediumTR": "Heykel",
      "images": [
        {
          "path": "images/artwork/israfilin-zurnasi/15mart1.png",
          "isMain": false,
          "caption": ""
        },
        {
          "path": "images/artwork/israfilin-zurnasi/IMG_0428.JPG",
          "isMain": false,
          "caption": ""
        },
        {
          "path": "images/artwork/israfilin-zurnasi/IMG_0429.JPG",
          "isMain": true,
          "caption": ""
        },
        {
          "path": "images/artwork/israfilin-zurnasi/IMG_0450.JPG",
          "isMain": false,
          "caption": ""
        },
        {
          "path": "images/artwork/israfilin-zurnasi/IMG_0449.JPG",
          "isMain": false,
          "caption": ""
        },
        {
          "path": "images/artwork/israfilin-zurnasi/IMG_0445.JPG",
          "isMain": false,
          "caption": ""
        }
      ],
      "materials": [
        {
          "id": "m-1774895213717",
          "type": "image-gallery",
          "label": "Process",
          "content": "",
          "contentTR": "",
          "images": [
            {
              "path": "images/artwork/israfilin-zurnasi/israfilinzurnasi_page-0012.jpg",
              "caption": ""
            },
            {
              "path": "images/artwork/israfilin-zurnasi/israfilinzurnasi_page-0013.jpg",
              "caption": ""
            },
            {
              "path": "images/artwork/israfilin-zurnasi/israfilinzurnasi_page-0014.jpg",
              "caption": ""
            },
            {
              "path": "images/artwork/israfilin-zurnasi/israfilinzurnasi_page-0015.jpg",
              "caption": ""
            },
            {
              "path": "images/artwork/israfilin-zurnasi/israfilinzurnasi_page-0016.jpg",
              "caption": ""
            },
            {
              "path": "images/artwork/israfilin-zurnasi/israfilinzurnasi_page-0017.jpg",
              "caption": ""
            },
            {
              "path": "images/artwork/israfilin-zurnasi/israfilinzurnasi_page-0018.jpg",
              "caption": ""
            }
          ],
          "path": ""
        },
        {
          "id": "m-1774895373904",
          "type": "gif",
          "label": "Time Lapse 1 hour",
          "content": "",
          "contentTR": "",
          "images": [],
          "path": ""
        },
        {
          "id": "m-1774895402798",
          "type": "pdf",
          "label": "Pdf",
          "content": "",
          "contentTR": "",
          "images": [],
          "path": "images/artwork/israfilin-zurnasi/israfilinzurnasi.pdf"
        }
      ],
      "displayImage": null,
      "featured": true,
      "workType": "3d",
      "category": "sculpture"
    },
    {
      "id": "ar-1775207222437",
      "title": "untitled",
      "titleTR": "isimsiz",
      "year": "2024",
      "desc": "",
      "descTR": "",
      "medium": "carboard print on paper",
      "mediumTR": "kağıt üzerine karton baskı",
      "images": [
        {
          "path": "images/artwork/prints/IMG_1291.jpg",
          "isMain": true,
          "caption": ""
        },
        {
          "path": "images/artwork/prints/IMG_1298.jpg",
          "isMain": false,
          "caption": ""
        }
      ],
      "materials": [],
      "displayImage": "images/artwork/prints/IMG_1298.jpg",
      "featured": true,
      "workType": "2d",
      "category": "print"
    },
    {
      "id": "ar-1775213858215",
      "title": "untitled",
      "titleTR": "isimsiz",
      "year": "2025",
      "desc": "It was created while the lathe was running, using a taut string soaked in ink.",
      "descTR": "torna çalışırken, üzerinde mürekkep yedirilmiş gergin ip yardımı ile oluşturuldu.",
      "medium": "ink",
      "mediumTR": "mürekkep",
      "images": [
        {
          "path": "images/artwork/prints/IMG_1284.jpg",
          "isMain": true,
          "caption": ""
        }
      ],
      "materials": [],
      "displayImage": "images/artwork/prints/IMG_1284.jpg",
      "featured": false,
      "workType": "2d",
      "category": "drawing"
    },
    {
      "id": "ar-1775214048146",
      "title": "untitled",
      "titleTR": "isimsiz",
      "year": "2025",
      "desc": "It was created while the lathe was running, using a taut string soaked in ink.",
      "descTR": "torna çalışırken, üzerinde mürekkep yedirilmiş gergin ip yardımı ile oluşturuldu.",
      "medium": "ink",
      "mediumTR": "mürekkep",
      "images": [
        {
          "path": "images/artwork/prints/IMG_1267.jpg",
          "isMain": true,
          "caption": ""
        }
      ],
      "materials": [],
      "displayImage": "images/artwork/prints/IMG_1267.jpg",
      "featured": false,
      "workType": "2d",
      "category": "drawing"
    },
    {
      "id": "ar-1775214222850",
      "title": "untitled",
      "titleTR": "isimsiz",
      "year": "2023",
      "desc": "",
      "descTR": "",
      "medium": "linoleum print on paper",
      "mediumTR": "kağıt üzerine linolyum baskı",
      "images": [
        {
          "path": "images/artwork/prints/IMG_1306.jpg",
          "isMain": true,
          "caption": ""
        }
      ],
      "materials": [],
      "displayImage": "images/artwork/prints/IMG_1306.jpg",
      "featured": false,
      "workType": "2d",
      "category": "print"
    }
  ],
  "poems": [
    {
      "id": "poem-1",
      "title": "Poem Title One",
      "titleTR": "Şiir Başlık Bir",
      "year": "2024",
      "body": "Add your full poem text here.\nEach line break is preserved exactly.\nThis is where your verses live.\n \nA second stanza can go here,\nseparated by a blank line.",
      "bodyTR": "Şiir metninizi buraya ekleyin.\nHer satır sonu korunur.\nDizeleriniz burada yer alacak.\n \nİkinci kıta buraya gelebilir,\nboş bir satırla ayrılmış şekilde."
    },
    {
      "id": "poem-2",
      "title": "Poem Title Two",
      "titleTR": "Şiir Başlık İki",
      "year": "2024",
      "body": "Second poem goes here.\nAdd as many lines as you like.",
      "bodyTR": "İkinci şiir buraya gelir.\nİstediğiniz kadar satır ekleyebilirsiniz."
    },
    {
      "id": "poem-3",
      "title": "Poem Title Three",
      "titleTR": "Şiir Başlık Üç",
      "year": "2023",
      "body": "Third poem goes here.",
      "bodyTR": "Üçüncü şiir buraya gelir."
    }
  ],
  "articles": [
    {
      "id": "article-1",
      "title": "Article Title One",
      "titleTR": "Makale Başlık Bir",
      "year": "2024",
      "type": "Essay",
      "typeTR": "Deneme",
      "body": "Add your full article text here. This is the body of the essay — you can write as much as you need.\n \nA second paragraph of the article continues here.",
      "bodyTR": "Makale metninizi buraya ekleyin.\n \nMakalenin ikinci paragrafı burada devam eder."
    },
    {
      "id": "article-2",
      "title": "Article Title Two",
      "titleTR": "Makale Başlık İki",
      "year": "2023",
      "type": "Criticism",
      "typeTR": "Eleştiri",
      "body": "Second article body goes here.",
      "bodyTR": "İkinci makale metni buraya gelir."
    }
  ],
  "books": [
    {
      "id": "stain",
      "title": "Stain",
      "titleTR": "Leke",
      "year": "2026",
      "pdf": "books/stainturkish.pdf",
      "cover": null,
      "allowDownload": true,
      "desc": "A collection of poems.",
      "descTR": "Şiirler derlemesi."
    }
  ],
  "projects": [
    {
      "id": "proj-1",
      "title": "Project Title One",
      "titleTR": "Proje Başlık Bir",
      "desc": "A short description of this ongoing project.",
      "descTR": "Bu devam eden projenin kısa açıklaması.",
      "status": "ongoing",
      "images": [],
      "materials": [],
      "displayImage": null,
      "featured": false,
      "workType": "3d"
    }
  ],
  "texts": {
    "aboutEN": "Write your biography or artist statement here. Who you are, where you come from, what you make and why.\n \nA second paragraph about your practice — the themes you return to, the tensions that drive your work.",
    "aboutTR": "Biyografinizi buraya yazın. Kim olduğunuzu, nereden geldiğinizi, ne ürettiğinizi ve neden.\n \nPratiğiniz hakkında ikinci paragraf — döndüğünüz temalar, çalışmalarınızı yönlendiren gerilimler.",
    "contactNote": "Collaborations, exhibitions, publications.",
    "contactNoteTR": "İşbirlikleri, sergiler, yayınlar.",
    "featuredArtworks": "artwork-1774889675037 , ar-1774893786854 , ar-1774892777816"
  },
  "heroSlider": {
    "images": [
      {
        "path": "images/artwork/hayatdonerdeneme1/hayatdonerdeneme1-3.jpg",
        "artworkId": "artwork-1774889675037",
        "artworkTitle": "hayat döner attempt 1"
      },
      {
        "path": "images/artwork/prints/IMG_1298.jpg",
        "artworkId": "ar-1775207222437",
        "artworkTitle": "untitled"
      },
      {
        "path": "images/artwork/israfilin-zurnasi/IMG_0428.JPG",
        "artworkId": "ar-1774893786854",
        "artworkTitle": "gabriel's clarion"
      },
      {
        "path": "images/artwork/israfilin-zurnasi/IMG_0450.JPG",
        "artworkId": "ar-1774893786854",
        "artworkTitle": "gabriel's clarion"
      }
    ],
    "slideCount": 5,
    "randomize": true
  },
  "categories": [
    {
      "en": "print",
      "tr": "baskı"
    },
    {
      "en": "drawing",
      "tr": "çizim"
    },
    {
      "en": "sculpture",
      "tr": "heykel"
    }
  ]
};
