/* ═══════════════════════════════════════════════════════════════════
   ENGINE.JS — site logic for tarik yigit / veretrir.art
   Do not edit this file. Edit content.js instead.
═══════════════════════════════════════════════════════════════════ */

/* ── Language ───────────────────────────── */
let currentLang = localStorage.getItem('lang') || 'en';

const T = {
  artworks:    { en:'Artworks',   tr:'Eserler'  },
  writings:    { en:'Writings',   tr:'Yazılar'  },
  about:       { en:'About',      tr:'Hakkında' },
  contact:     { en:'Contact',    tr:'İletişim' },
  ongoing:     { en:'Ongoing',    tr:'Devam'    },
  planned:     { en:'Planned',    tr:'Planlandı'},
  close:       { en:'Close',      tr:'Kapat'    },
  back:        { en:'Back',       tr:'Geri'     },
  works:       { en:'works',      tr:'eser'     },
  about_work:  { en:'About this work', tr:'Bu eser hakkında' },
  add_img:     { en:'add image',  tr:'görsel ekle' },
  add_photos:  { en:'Additional photos', tr:'Ek fotoğraflar' },
  view3d:      { en:'View 3D model', tr:'3D modeli görüntüle' },
  all:         { en:'All',        tr:'Tümü'     },
  poem:        { en:'Poem',       tr:'Şiir'     },
  article:     { en:'Article',    tr:'Makale'   },
  book:        { en:'Book',       tr:'Kitap'    },
  pages:       { en:'pages',      tr:'sayfa'    },
};

function t(key) { return T[key] ? (T[key][currentLang] || T[key].en) : key; }
function tObj(obj) { return obj ? (obj[currentLang] || obj.en || '') : ''; }
const $ = id => document.getElementById(id);

function setLang(l) {
  currentLang = l;
  localStorage.setItem('lang', l);
  $('b-en').classList.toggle('on', l==='en');
  $('b-tr').classList.toggle('on', l==='tr');
  document.documentElement.lang = l;
  // re-render data-en/data-tr attributes
  document.querySelectorAll('[data-en]').forEach(el => {
    const v = el.getAttribute('data-' + l) || el.getAttribute('data-en');
    if (v !== null) el.innerHTML = v;
  });
  // trigger page-specific refresh
  if (typeof onLangChange === 'function') onLangChange(l);
}

/* ── Init (runs on every page) ─────────── */
function initSite() {
  // set language buttons
  const ben = $('b-en'), btr = $('b-tr');
  if (ben) ben.classList.toggle('on', currentLang==='en');
  if (btr) btr.classList.toggle('on', currentLang==='tr');
  document.documentElement.lang = currentLang;

  // ig link
  const ig = $('ig-link');
  if (ig) ig.href = SITE.instagram;

  // footer
  const fn = $('footer-name'), fd = $('footer-domain');
  if (fn) fn.textContent = SITE.name;
  if (fd) fd.textContent = SITE.domain;

  // data-en/data-tr static labels
  document.querySelectorAll('[data-en]').forEach(el => {
    const v = el.getAttribute('data-' + currentLang) || el.getAttribute('data-en');
    if (v) el.innerHTML = v;
  });

  // page transitions
  document.addEventListener('click', onLinkClick);
}

/* ── Page transitions ───────────────────── */
function onLinkClick(e) {
  const a = e.target.closest('a[href]');
  if (!a) return;
  const href = a.getAttribute('href');
  if (!href || href.startsWith('#') || href.startsWith('mailto:') ||
      href.startsWith('http') || a.target === '_blank') return;
  e.preventDefault();
  navigateTo(href);
}

function navigateTo(href) {
  document.body.classList.add('is-leaving');
  setTimeout(() => { window.location.href = href; }, 370);
}

/* ── Animate page in ────────────────────── */
function animateIn() {
  document.body.classList.add('is-entering');
  setTimeout(() => document.body.classList.remove('is-entering'), 600);
}

/* ═══════════════════════════════════════
   HOME PAGE
═══════════════════════════════════════ */

/* Hero slideshow */
let hCur=0, hTotal=0, hTimer;

function renderHero() {
  const nameEl = $('hero-name');
  if (nameEl) nameEl.textContent = SITE.name;

  const track = $('heroTrack');
  if (!track) return;

  const imgs = (HERO_IMAGES && HERO_IMAGES.length) ? HERO_IMAGES : ['','',''];
  hTotal = imgs.length;
  track.innerHTML = '';

  imgs.forEach(src => {
    const s = document.createElement('div');
    s.className = 'hero-slide';
    s.innerHTML = src
      ? `<img src="${src}" alt="">`
      : `<div class="hero-slide-ph"><span>add artwork photo</span></div>`;
    track.appendChild(s);
  });

  heroInitDots();
  clearInterval(hTimer);
  hTimer = setInterval(() => heroMove(1), 5000);
}

function heroInitDots() {
  const el = $('heroDots');
  if (!el) return;
  el.innerHTML = '';
  for (let i=0;i<hTotal;i++) {
    const d = document.createElement('button');
    d.className = 'hero-dot'+(i===0?' on':'');
    d.onclick = () => heroGoTo(i);
    el.appendChild(d);
  }
  heroGoTo(0);
}

function heroGoTo(n) {
  hCur = (n+hTotal)%hTotal;
  const track = $('heroTrack');
  if (track) track.style.transform = `translateX(-${hCur*100}%)`;
  const dots = $('heroDots');
  if (dots) dots.querySelectorAll('.hero-dot').forEach((d,i) => d.classList.toggle('on',i===hCur));
}

function heroMove(dir) {
  clearInterval(hTimer);
  heroGoTo(hCur+dir);
  hTimer = setInterval(() => heroMove(1), 5000);
}

/* Swipe on hero */
window.addEventListener('DOMContentLoaded', () => {
  const track = $('heroTrack');
  if (!track) return;
  let dx=0;
  track.addEventListener('mousedown',  e=>dx=e.clientX);
  track.addEventListener('touchstart', e=>dx=e.touches[0].clientX,{passive:true});
  track.addEventListener('mouseup',    e=>{if(Math.abs(e.clientX-dx)>40)heroMove(e.clientX<dx?1:-1);});
  track.addEventListener('touchend',   e=>{const d=e.changedTouches[0].clientX-dx;if(Math.abs(d)>40)heroMove(d<0?1:-1);});
});

function renderRecentGrid() {
  const grid = $('recentGrid');
  if (!grid) return;
  const recent = ARTWORKS.slice(0,4);
  grid.innerHTML = recent.map((aw,i) => artCardHTML(aw,i)).join('');
  // wire up clicks to artworks page
  grid.querySelectorAll('.aw-card').forEach((card, i) => {
    card.onclick = () => navigateTo(`artworks.html?id=${recent[i].id}`);
  });
}

function renderProjects() {
  const list = $('projectsList');
  if (!list) return;
  list.innerHTML = PROJECTS.map(pr => `
    <div class="project-row">
      <div>
        <div class="project-row-name">${tObj(pr.title)}</div>
        <div class="project-row-desc">${tObj(pr.desc)}</div>
      </div>
      <span class="pr-tag tag-${pr.status}">
        ${t(pr.status)}
      </span>
    </div>
  `).join('');
}

/* ═══════════════════════════════════════
   ARTWORKS ARCHIVE
═══════════════════════════════════════ */

/* Active filters */
let activeFilters = { type:null, year:null, series:null };

function buildFilters() {
  const types   = [...new Set(ARTWORKS.map(a=>a.type))].sort();
  const years   = [...new Set(ARTWORKS.map(a=>a.year))].sort((a,b)=>b-a);
  const series  = [...new Set(ARTWORKS.map(a=>a.series).filter(Boolean))].sort();

  const ftEl = $('filterType');
  const fyEl = $('filterYear');
  const fsEl = $('filterSeries');
  if (!ftEl) return;

  ftEl.innerHTML = chipHTML('All',   null,  'type')  +
    types.map(v=>chipHTML(capitalize(v), v, 'type')).join('');
  fyEl.innerHTML = chipHTML('All',   null,  'year')  +
    years.map(v=>chipHTML(v,           v,  'year')).join('');
  fsEl.innerHTML = series.length
    ? chipHTML('All',  null,  'series') + series.map(v=>chipHTML(capitalize(v), v, 'series')).join('')
    : '';

  updateCount();
}

function chipHTML(label, value, key) {
  const active = activeFilters[key] === value ? 'on' : '';
  return `<button class="filter-chip ${active}" onclick="setFilter('${key}',${JSON.stringify(value)})">${label}</button>`;
}

function setFilter(key, value) {
  activeFilters[key] = activeFilters[key] === value ? null : value;
  buildFilters(); // rebuild chips with updated state
  renderArchive();
}

function resetFilters() {
  activeFilters = {type:null, year:null, series:null};
  buildFilters();
  renderArchive();
}

function filteredWorks() {
  return ARTWORKS.filter(aw => {
    if (activeFilters.type   && aw.type   !== activeFilters.type)   return false;
    if (activeFilters.year   && aw.year   !== activeFilters.year)   return false;
    if (activeFilters.series && aw.series !== activeFilters.series) return false;
    return true;
  });
}

function updateCount() {
  const cnt = $('archiveCount');
  if (cnt) cnt.textContent = filteredWorks().length;
}

function renderArchive() {
  const grid = $('archiveGrid');
  const empty = $('archiveEmpty');
  if (!grid) return;

  const works = filteredWorks();
  updateCount();

  if (works.length === 0) {
    grid.innerHTML = '';
    if (empty) empty.style.display = 'block';
    return;
  }
  if (empty) empty.style.display = 'none';

  grid.innerHTML = works.map(aw => artCardHTML(aw)).join('');
  grid.querySelectorAll('.aw-card').forEach((card, i) => {
    card.onclick = () => openDetail(works[i]);
  });
}

function artCardHTML(aw) {
  const title = tObj(aw.title);
  return `
  <div class="aw-card">
    ${aw.mainImage
      ? `<img src="${aw.mainImage}" alt="${title}">`
      : `<div class="aw-card-ph"><div class="aw-card-ph-cross"></div><span class="aw-card-ph-lbl">image</span></div>`
    }
    <div class="aw-card-overlay">
      <div class="aw-card-title">${title}</div>
      <div class="aw-card-meta">${aw.year} · ${capitalize(aw.type)}</div>
    </div>
  </div>`;
}

/* ── Artwork Detail ─────────────────────── */
let detailSavedY = 0;

function openDetail(aw) {
  detailSavedY = window.scrollY;
  const panel = $('detailPanel');
  const body  = $('detailContent');
  const barTitle = $('detailBarTitle');
  if (!panel || !body) return;

  const title  = tObj(aw.title);
  const medium = tObj(aw.medium);
  const desc   = tObj(aw.description);

  barTitle.textContent = title;

  const heroHtml = aw.mainImage
    ? `<img class="detail-hero" src="${aw.mainImage}" alt="${title}">`
    : `<div class="detail-hero-ph"><span>${t('add_img')}</span></div>`;

  const gallerySlots = Math.max((aw.images||[]).length, 3);
  const galleryHtml = Array.from({length:gallerySlots}, (_,i) => {
    return aw.images && aw.images[i]
      ? `<div class="detail-gal-img"><img src="${aw.images[i]}" alt="${title} ${i+1}"></div>`
      : `<div class="detail-gal-ph"><span>${t('add_img')}</span></div>`;
  }).join('');

  const descHtml = desc.split(/\n\n+/).map(p=>`<p>${p}</p>`).join('');

  const meta = [aw.year, medium, aw.dimensions, aw.series ? capitalize(aw.series) : '']
    .filter(Boolean).join(' · ');

  const model3dBtn = aw.model3d
    ? `<button class="model3d-btn" onclick="openViewer('${aw.model3d}')">${t('view3d')}</button>`
    : '';

  body.innerHTML = `
    ${heroHtml}
    <div class="detail-title">${title}</div>
    <div class="detail-meta">${meta}</div>
    ${model3dBtn}
    <div class="detail-sec">${t('about_work')}</div>
    <div class="detail-desc">${descHtml}</div>
    <div class="detail-sec">${t('add_photos')}</div>
    <div class="detail-gallery">${galleryHtml}</div>
  `;

  document.body.style.overflow = 'hidden';
  panel.scrollTop = 0;
  panel.classList.add('open');

  // update URL without navigating
  history.pushState({aw: aw.id}, '', `artworks.html?id=${aw.id}`);
}

function closeDetail() {
  const panel = $('detailPanel');
  if (!panel) return;
  panel.classList.remove('open');
  document.body.style.overflow = '';
  window.scrollTo(0, detailSavedY);
  history.pushState({}, '', 'artworks.html');
}

/* ═══════════════════════════════════════
   WRITINGS PAGE
═══════════════════════════════════════ */

function wrTab(name) {
  document.querySelectorAll('.wr-tab').forEach((b,i) => {
    const names = ['books','poems','articles'];
    b.classList.toggle('on', names[i]===name);
  });
  ['books','poems','articles'].forEach(n => {
    const el = $('wr-'+n);
    if (el) el.classList.toggle('on', n===name);
  });
}

function renderBooks() {
  const grid = $('booksGrid');
  if (!grid) return;
  grid.innerHTML = WRITINGS.books.map(bk => {
    const title = tObj(bk.title);
    const cover = bk.cover
      ? `<img src="${bk.cover}" alt="${title}">`
      : `<div class="book-card-cover-ph"><div class="aw-card-ph-cross"></div><span>${t('add_img')}</span></div>`;
    return `
    <div class="book-card" onclick="openBook(${JSON.stringify(bk.id)})">
      <div class="book-card-cover">${cover}</div>
      <div class="book-card-info">
        <div class="book-card-title">${title}</div>
        <div class="book-card-meta">${bk.year} · ${bk.pages.length} ${t('pages')}</div>
      </div>
    </div>`;
  }).join('');
}

function renderPoems() {
  const list = $('poemsList');
  if (!list) return;
  list.innerHTML = WRITINGS.poems.map(pm => `
    <div class="poem-row" onclick="openReading('poem', ${JSON.stringify(pm.id)})">
      <span class="poem-row-title">${tObj(pm.title)}</span>
      <span class="poem-row-year">${pm.year}</span>
    </div>
  `).join('');
}

function renderArticles() {
  const list = $('articlesList');
  if (!list) return;
  list.innerHTML = WRITINGS.articles.map(ar => `
    <div class="article-row" onclick="openReading('article', ${JSON.stringify(ar.id)})">
      <span class="article-row-title">${tObj(ar.title)}</span>
      <div class="article-row-right">
        <span class="article-row-type">${tObj(ar.type)}</span>
        <span class="article-row-year">${ar.year}</span>
      </div>
    </div>
  `).join('');
}

/* ── Reading overlay (poem/article) ─────── */
let readingSavedY = 0;

function openReading(type, id) {
  readingSavedY = window.scrollY;
  const overlay = $('readingOverlay');
  const body    = $('readingBody');
  const barTitle= $('readingBarTitle');
  if (!overlay || !body) return;

  let html = '';
  if (type === 'poem') {
    const pm = WRITINGS.poems.find(p=>p.id===id);
    if (!pm) return;
    barTitle.textContent = tObj(pm.title);
    html = `
      <div class="reading-title">${tObj(pm.title)}</div>
      <div class="reading-meta">${pm.year} · ${t('poem')}</div>
      <div class="reading-poem-body">${tObj(pm.body)}</div>
    `;
  } else if (type === 'article') {
    const ar = WRITINGS.articles.find(a=>a.id===id);
    if (!ar) return;
    barTitle.textContent = tObj(ar.title);
    const bodyHtml = tObj(ar.body).split(/\n\n+/).map(p=>`<p>${p}</p>`).join('');
    html = `
      <div class="reading-title">${tObj(ar.title)}</div>
      <div class="reading-meta">${ar.year} · ${tObj(ar.type)}</div>
      <div class="reading-article-body">${bodyHtml}</div>
    `;
  }

  body.innerHTML = html;
  document.body.style.overflow = 'hidden';
  overlay.scrollTop = 0;
  overlay.classList.add('open');
}

function closeReading() {
  const overlay = $('readingOverlay');
  if (overlay) overlay.classList.remove('open');
  document.body.style.overflow = '';
  window.scrollTo(0, readingSavedY);
}

/* ── Book reader ─────────────────────────── */
let bookData = null;
let bookSpread = 0; // index of left page (0,2,4,...)

function openBook(id) {
  const bk = WRITINGS.books.find(b=>b.id===id);
  if (!bk) return;
  bookData = bk;
  bookSpread = 0;

  const overlay = $('bookOverlay');
  $('bookBarTitle').textContent = tObj(bk.title);
  overlay.classList.add('open');
  document.body.style.overflow = 'hidden';
  renderBookSpread(false);
}

function closeBook() {
  const overlay = $('bookOverlay');
  if (overlay) overlay.classList.remove('open');
  document.body.style.overflow = '';
  bookData = null;
}

function renderBookSpread(animate) {
  if (!bookData) return;
  const pages = bookData.pages;
  const totalPages = pages.length;

  const L = $('bookPageL');
  const R = $('bookPageR');
  const prevBtn = $('bookPrev');
  const nextBtn = $('bookNext');
  const numEl   = $('bookPageNum');

  const leftIdx  = bookSpread;
  const rightIdx = bookSpread + 1;

  const leftText  = leftIdx  < totalPages ? tObj(pages[leftIdx])  : '';
  const rightText = rightIdx < totalPages ? tObj(pages[rightIdx]) : '';

  if (animate) {
    L.classList.add('flip-out'); R.classList.add('flip-out');
    setTimeout(() => {
      L.classList.remove('flip-out'); R.classList.remove('flip-out');
      setBookPageContent(L, leftText,  leftIdx+1,  totalPages);
      setBookPageContent(R, rightText, rightIdx+1, totalPages);
      L.classList.add('flip-in'); R.classList.add('flip-in');
      setTimeout(() => { L.classList.remove('flip-in'); R.classList.remove('flip-in'); }, 220);
    }, 200);
  } else {
    setBookPageContent(L, leftText,  leftIdx+1,  totalPages);
    setBookPageContent(R, rightText, rightIdx+1, totalPages);
  }

  prevBtn.disabled = bookSpread <= 0;
  nextBtn.disabled = bookSpread + 2 >= totalPages;

  const endPage = Math.min(rightIdx+1, totalPages);
  numEl.textContent = `${leftIdx+1}–${endPage} / ${totalPages}`;
}

function setBookPageContent(el, text, num, total) {
  el.innerHTML = text
    ? `<div class="book-page-text">${text}</div><div class="book-page-num-inside">${num}</div>`
    : `<div class="book-page-num-inside">&nbsp;</div>`;
}

function bookFlip(dir) {
  if (!bookData) return;
  const total = bookData.pages.length;
  const next = bookSpread + dir * 2;
  if (next < 0 || next >= total) return;
  bookSpread = next;
  renderBookSpread(true);
}

/* ═══════════════════════════════════════
   UTILS
═══════════════════════════════════════ */
function capitalize(s) {
  if (!s) return '';
  return s.charAt(0).toUpperCase() + s.slice(1);
}

/* ── About page re-render on lang change ── */
function onLangChange(l) {
  // artworks archive
  const grid = $('archiveGrid');
  if (grid && ARTWORKS) renderArchive();

  // projects on home
  renderProjects();

  // writings
  renderBooks(); renderPoems(); renderArticles();

  // about text
  const aboutText = $('aboutText');
  if (aboutText && SITE) {
    aboutText.innerHTML = (l==='tr' ? SITE.about.tr : SITE.about.en)
      .split(/\n\n+/).map(p=>`<p>${p.replace(/\n/g,'<br>')}</p>`).join('');
  }

  // contact
  const cnote = $('contactNote');
  if (cnote) cnote.textContent = l==='tr' ? SITE.contact.note.tr : SITE.contact.note.en;
}
